package com.sterlingsworld.feature.game.games.aol

import com.sterlingsworld.feature.game.games.symptomstriker.EnemyDefinition
import com.sterlingsworld.feature.game.games.symptomstriker.EncounterDefinition
import com.sterlingsworld.feature.game.games.symptomstriker.MoveDefinition
import com.sterlingsworld.feature.game.games.symptomstriker.MoveType
import com.sterlingsworld.feature.game.games.symptomstriker.StatusKey

// ── Armor of Light specific encounter and move data ────────────────────────
// Extracted from the source HTML (app/src/main/assets/games/AOL/index.html).

internal val AOL_MOVE_LIBRARY: Map<String, MoveDefinition> = mapOf(
    "prayer_shield" to MoveDefinition(
        id = "prayer_shield", label = "Prayer Shield", subLabel = "+2 Grace",
        type = MoveType.RECOVERY, spoonCost = 0,
        healPercent = 0.20f, spoonHeal = 2,
        description = "Prayer Shield. Heal 20% max HP and regain 2 Grace.",
    ),
    "hymn_of_peace" to MoveDefinition(
        id = "hymn_of_peace", label = "Hymn of Peace", subLabel = "+1 Grace",
        type = MoveType.RECOVERY, spoonCost = 0,
        healPercent = 0.20f, spoonHeal = 1,
        description = "Hymn of Peace. Heal 20% max HP and regain 1 Grace.",
    ),
    "scripture_song" to MoveDefinition(
        id = "scripture_song", label = "Scripture Song", subLabel = "+1 Grace",
        type = MoveType.RECOVERY, spoonCost = 0,
        healPercent = 0.10f, spoonHeal = 1,
        description = "Scripture Song. Heal 10% max HP and regain 1 Grace.",
    ),
    "charity_strike" to MoveDefinition(
        id = "charity_strike", label = "Charity Strike", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 40,
        description = "Charity Strike. Deals 40 damage.",
    ),
    "tithe_hammer" to MoveDefinition(
        id = "tithe_hammer", label = "Tithe Hammer", subLabel = "Cost: 2",
        type = MoveType.ATTACK, spoonCost = 2, power = 70,
        description = "Tithe Hammer. Deals 70 damage.",
    ),
    "fasting_light" to MoveDefinition(
        id = "fasting_light", label = "Fasting Light", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 40,
        description = "Fasting Light. Deals 40 damage.",
    ),
    "temperance_blade" to MoveDefinition(
        id = "temperance_blade", label = "Temperance Blade", subLabel = "Cures Poison",
        type = MoveType.CURE, spoonCost = 1, healPercent = 0.10f, spoonHeal = 0,
        clearsStatus = StatusKey.OVERHEATED,
        description = "Temperance Blade. Heals 10% max HP and clears Poison.",
    ),
    "forgiveness_palm" to MoveDefinition(
        id = "forgiveness_palm", label = "Forgiveness Palm", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 40,
        description = "Forgiveness Palm. Deals 40 damage.",
    ),
    "peace_covenant" to MoveDefinition(
        id = "peace_covenant", label = "Peace Covenant", subLabel = "Breaks Chains",
        type = MoveType.CURE, spoonCost = 1, healPercent = 0.25f, spoonHeal = 0,
        clearsStatus = StatusKey.LOCKED,
        description = "Peace Covenant. Heals 25% max HP and breaks Chains.",
    ),
    "diligence_spark" to MoveDefinition(
        id = "diligence_spark", label = "Diligence Spark", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 60,
        description = "Diligence Spark. Deals 60 damage.",
    ),
    "wake_up_call" to MoveDefinition(
        id = "wake_up_call", label = "Wake-Up Call", subLabel = "Clears Sloth",
        type = MoveType.CURE, spoonCost = 2, power = 55,
        clearsStatus = StatusKey.FOGGED,
        description = "Wake-Up Call. Deals 55 damage and clears Sloth.",
    ),
    "humility_strike" to MoveDefinition(
        id = "humility_strike", label = "Humility Strike", subLabel = "Cost: 2",
        type = MoveType.ATTACK, spoonCost = 2, power = 75,
        description = "Humility Strike. Deals 75 damage.",
    ),
    "servants_heart" to MoveDefinition(
        id = "servants_heart", label = "Servant's Heart", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 60,
        description = "Servant's Heart. Deals 60 damage.",
    ),
    "gratitude_beam" to MoveDefinition(
        id = "gratitude_beam", label = "Gratitude Beam", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 60,
        description = "Gratitude Beam. Deals 60 damage.",
    ),
    "contentment_shield" to MoveDefinition(
        id = "contentment_shield", label = "Contentment Shield", subLabel = "Cost: 3",
        type = MoveType.ATTACK, spoonCost = 3, power = 85,
        description = "Contentment Shield. Deals 85 damage.",
    ),
    "purity_flash" to MoveDefinition(
        id = "purity_flash", label = "Purity Flash", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 60,
        description = "Purity Flash. Deals 60 damage.",
    ),
    "chastity_ward" to MoveDefinition(
        id = "chastity_ward", label = "Chastity Ward", subLabel = "Cost: 2",
        type = MoveType.ATTACK, spoonCost = 2, power = 60,
        description = "Chastity Ward. Deals 60 damage.",
    ),
    "hope_blade" to MoveDefinition(
        id = "hope_blade", label = "Hope Blade", subLabel = "Cost: 1",
        type = MoveType.ATTACK, spoonCost = 1, power = 60,
        description = "Hope Blade. Deals 60 damage.",
    ),
    "resurrection_light" to MoveDefinition(
        id = "resurrection_light", label = "Resurrection Light", subLabel = "Banishes Despair",
        type = MoveType.CURE, spoonCost = 2, power = 80,
        clearsStatus = StatusKey.VERTIGO,
        description = "Resurrection Light. Deals 80 damage and clears Despair.",
    ),
    "heros_roar" to MoveDefinition(
        id = "heros_roar", label = "Leap of Faith", subLabel = "Costs HP",
        type = MoveType.ATTACK, spoonCost = 0,
        description = "Fight through the pain. Costs HP instead of Grace. Hits harder at low health.",
    )
)

internal val AOL_ENCOUNTERS: List<EncounterDefinition> = listOf(
    EncounterDefinition(
        index = 0,
        title = "I: The Gilded Hall",
        accentColor = 0xFFFFD700,
        enemy = EnemyDefinition(
            id = "greed",
            name = "Greed",
            sprite = "($$$)\n~ GREED ~",
            maxHp = 40,
            normalPower = 10,
            specialPower = 12,
            specialChance = 0.20f,
            specialChanceEnraged = 0.40f,
            appliesStatus = StatusKey.LOCKED,
            specialDescription = "Greed clutches \u2014 muscles seized, attacks cost +1 Grace",
        ),
        playerStartHp = 80,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "hymn_of_peace", "charity_strike", "tithe_hammer"),
        intro = "Gold coins litter the floor. A bloated king clutches his chalice and sneers at you.",
        symptomsDesc = "Greed hoards what should be shared. The virtue of Charity defeats him by giving freely.",
    ),
    EncounterDefinition(
        index = 1,
        title = "II: The Rotting Feast",
        accentColor = 0xFF8B6B3E,
        enemy = EnemyDefinition(
            id = "gluttony",
            name = "Gluttony",
            sprite = "(oOo)\n~ GLUTTONY ~",
            maxHp = 60,
            normalPower = 12,
            specialPower = 15,
            specialChance = 0.25f,
            specialChanceEnraged = 0.45f,
            appliesStatus = StatusKey.OVERHEATED,
            specialDescription = "Toxic Bile \u2014 poisoned for 3 turns",
        ),
        playerStartHp = 90,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "fasting_light", "temperance_blade"),
        intro = "The stench of rot fills the air. A massive creature devours everything in sight.",
        symptomsDesc = "Gluttony consumes without gratitude. The virtue of Temperance defeats it through self-control.",
    ),
    EncounterDefinition(
        index = 2,
        title = "III: The Burning Pit",
        accentColor = 0xFFCC3333,
        enemy = EnemyDefinition(
            id = "wrath",
            name = "Wrath",
            sprite = "(!!!!)\n~ WRATH ~",
            maxHp = 60,
            normalPower = 15,
            specialPower = 18,
            specialChance = 0.30f,
            specialChanceEnraged = 0.50f,
            appliesStatus = StatusKey.LOCKED,
            specialDescription = "Chains of Wrath \u2014 locked in place, attacks cost +1 Grace",
        ),
        playerStartHp = 110,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "hymn_of_peace", "forgiveness_palm", "peace_covenant"),
        intro = "Chains rattle in the darkness. A demon of fire and fury breaks free.",
        symptomsDesc = "Wrath destroys through anger unchained. The virtue of Patience defeats it through forgiveness.",
    ),
    EncounterDefinition(
        index = 3,
        title = "IV: The Velvet Chamber",
        accentColor = 0xFF4A4A6A,
        enemy = EnemyDefinition(
            id = "sloth",
            name = "Sloth",
            sprite = "(z.z)\n~ SLOTH ~",
            maxHp = 90,
            normalPower = 18,
            specialPower = 20,
            specialChance = 0.30f,
            specialChanceEnraged = 0.55f,
            appliesStatus = StatusKey.FOGGED,
            specialDescription = "Sluggish Aura \u2014 one of your moves is blocked for 3 turns",
        ),
        playerStartHp = 120,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "diligence_spark", "wake_up_call"),
        intro = "Cobwebs hang like curtains. A shapeless shadow refuses to stir from its bed.",
        symptomsDesc = "Sloth neglects duty and prayer. The virtue of Diligence defeats it through faithful action.",
    ),
    EncounterDefinition(
        index = 4,
        title = "V: The Mirror Palace",
        accentColor = 0xFFC0C0E0,
        enemy = EnemyDefinition(
            id = "pride",
            name = "Pride",
            sprite = "(^_^)\n~ PRIDE ~",
            maxHp = 105,
            normalPower = 20,
            specialPower = 25,
            specialChance = 0.35f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.VERTIGO,
            specialDescription = "Blinding Hubris \u2014 your attacks have a miss chance for 3 turns",
        ),
        playerStartHp = 130,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "servants_heart", "humility_strike"),
        intro = "A perfect angel smiles at you from a thousand mirrors. But the smile never reaches its eyes.",
        symptomsDesc = "Pride places the self above God and neighbor. The virtue of Humility defeats it through service.",
    ),
    EncounterDefinition(
        index = 5,
        title = "VI: The Poison Garden",
        accentColor = 0xFF00CC66,
        enemy = EnemyDefinition(
            id = "envy",
            name = "Envy",
            sprite = "(s_s)\n~ ENVY ~",
            maxHp = 125,
            normalPower = 22,
            specialPower = 28,
            specialChance = 0.35f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.FOGGED,
            specialDescription = "Envious Blur \u2014 blocked move",
        ),
        playerStartHp = 150,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "gratitude_beam", "contentment_shield"),
        intro = "Poisonous flowers bloom in shadow. A serpent watches you with jealous, shifting eyes.",
        symptomsDesc = "Envy resents the blessings of others. The virtue of Gratitude defeats it through contentment.",
    ),
    EncounterDefinition(
        index = 6,
        title = "VII: The Crimson Tower",
        accentColor = 0xFFCC3388,
        enemy = EnemyDefinition(
            id = "lust",
            name = "Lust",
            sprite = "(~~~)\n~ LUST ~",
            maxHp = 140,
            normalPower = 25,
            specialPower = 30,
            specialChance = 0.35f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.FOGGED,
            specialDescription = "Illusory Haze \u2014 blocked move",
        ),
        playerStartHp = 180,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "purity_flash", "chastity_ward"),
        intro = "Hypnotic colors swirl through stained glass. A siren whispers false promises.",
        symptomsDesc = "Lust distorts love into selfish desire. The virtue of Chastity defeats it through purity of heart.",
    ),
    EncounterDefinition(
        index = 7,
        title = "VIII: Throne of Shadows",
        accentColor = 0xFF6633AA,
        enemy = EnemyDefinition(
            id = "acedia",
            name = "Acedia",
            sprite = "(. . .)\n~ VOID ~",
            maxHp = 175,
            normalPower = 30,
            specialPower = 35,
            specialChance = 0.40f,
            specialChanceEnraged = 0.70f,
            appliesStatus = StatusKey.VERTIGO,
            specialDescription = "Void Stare \u2014 deep despair causes attacks to miss",
        ),
        playerStartHp = 210,
        playerStartSpoons = 8,
        moves = listOf("prayer_shield", "scripture_song", "hope_blade", "resurrection_light"),
        intro = "Everything fades. A void entity sits upon a crumbling throne. It whispers that nothing matters.",
        symptomsDesc = "Acedia is spiritual despair that abandons hope. The virtue of Hope defeats it through trust in God.",
    ),
)
