package com.sterlingsworld.feature.game.games.symptomstriker

import androidx.annotation.DrawableRes
import com.sterlingsworld.R

// Symptom Striker specific encounter and move data.
// Extracted and adapted from app/src/main/assets/games/symptom-striker/index.html.

data class EnemyDefinition(
    val id: String,
    val name: String,
    @DrawableRes val portraitRes: Int? = null,
    val sprite: String,
    val maxHp: Int,
    val normalPower: Int,
    val specialPower: Int,
    /** Chance to use the status-inflicting special when HP is healthy. */
    val specialChance: Float,
    /** Chance to use the special when enraged (HP below rageTriggerPercent). */
    val specialChanceEnraged: Float,
    /** Which status this enemy inflicts with its special attack. */
    val appliesStatus: StatusKey,
    /** Player-facing description of the special attack shown in the battle log. */
    val specialDescription: String,
)

data class EncounterDefinition(
    val index: Int,
    val title: String,
    val accentColor: Long,
    val enemy: EnemyDefinition,
    val playerStartHp: Int,
    val playerStartSpoons: Int,
    /** Ordered list of move IDs available in this encounter before session unlocks are added. */
    val moves: List<String>,
    val intro: String,
    val symptomsDesc: String,
    /** Move unlocked for the remainder of the session when this encounter is cleared. */
    val rewardMoveId: String? = null,
)

internal val MOVE_LIBRARY: Map<String, MoveDefinition> = mapOf(
    "rest" to MoveDefinition(
        id = "rest",
        label = "Rest",
        subLabel = "+2 Spoons",
        type = MoveType.RECOVERY,
        spoonCost = 0,
        healPercent = 0.20f,
        spoonHeal = 2,
        description = "Take a rest. Heal 20% max HP and regain 2 Spoons.",
    ),
    "box_breathing" to MoveDefinition(
        id = "box_breathing",
        label = "Box Breathing",
        subLabel = "+1 Spoon",
        type = MoveType.RECOVERY,
        spoonCost = 0,
        healPercent = 0.15f,
        spoonHeal = 1,
        description = "Slow breath work. Heal 15% max HP and regain 1 Spoon.",
    ),
    "listen_music" to MoveDefinition(
        id = "listen_music",
        label = "Listen to Music",
        subLabel = "+1 Spoon",
        type = MoveType.RECOVERY,
        spoonCost = 0,
        healPercent = 0.10f,
        spoonHeal = 1,
        description = "A grounding playlist. Heal 10% max HP and regain 1 Spoon.",
    ),
    "light_stretching" to MoveDefinition(
        id = "light_stretching",
        label = "Light Stretch",
        subLabel = "Cost: 1",
        type = MoveType.ATTACK,
        spoonCost = 1,
        power = 20,
        description = "A gentle stretch routine. Deals 20 damage.",
    ),
    "physical_therapy" to MoveDefinition(
        id = "physical_therapy",
        label = "Physio",
        subLabel = "Cost: 2",
        type = MoveType.ATTACK,
        spoonCost = 2,
        power = 28,
        description = "Targeted physio routine. Deals 28 damage.",
    ),
    "adaptive_yoga" to MoveDefinition(
        id = "adaptive_yoga",
        label = "Adaptive Yoga",
        subLabel = "Cost: 1",
        type = MoveType.ATTACK,
        spoonCost = 1,
        power = 26,
        description = "A controlled sequence that deals 26 damage.",
    ),
    "cognitive_therapy" to MoveDefinition(
        id = "cognitive_therapy",
        label = "Cog Therapy",
        subLabel = "Clears Fog",
        type = MoveType.CURE,
        spoonCost = 1,
        power = 18,
        clearsStatus = StatusKey.FOGGED,
        description = "Cognitive therapy. Deals 18 damage and clears Fogged.",
    ),
    "cooling_vest" to MoveDefinition(
        id = "cooling_vest",
        label = "Cooling Vest",
        subLabel = "Clears Heat",
        type = MoveType.CURE,
        spoonCost = 1,
        healPercent = 0.10f,
        clearsStatus = StatusKey.OVERHEATED,
        description = "Cooling vest. Heals 10% max HP and clears Overheated.",
    ),
    "muscle_relaxant" to MoveDefinition(
        id = "muscle_relaxant",
        label = "Muscle Relax",
        subLabel = "Clears Lock",
        type = MoveType.CURE,
        spoonCost = 1,
        healPercent = 0.15f,
        clearsStatus = StatusKey.LOCKED,
        description = "Muscle relaxant. Heals 15% max HP and clears Locked.",
    ),
    "self_advocacy" to MoveDefinition(
        id = "self_advocacy",
        label = "Self-Advocacy",
        subLabel = "Clears Mask",
        type = MoveType.CURE,
        spoonCost = 2,
        power = 30,
        clearsStatus = StatusKey.MASKED,
        description = "Assert your reality. Deals 30 damage and clears Masked.",
    ),
    "corticosteroids" to MoveDefinition(
        id = "corticosteroids",
        label = "IV Steroids",
        subLabel = "Clears Blur",
        type = MoveType.CURE,
        spoonCost = 3,
        power = 34,
        clearsStatus = StatusKey.BLURRED,
        description = "A strong anti-inflammatory burst. Deals 34 damage and clears Blurred.",
    ),
    "nerve_meds" to MoveDefinition(
        id = "nerve_meds",
        label = "Nerve Meds",
        subLabel = "Clears Numb",
        type = MoveType.CURE,
        spoonCost = 2,
        power = 24,
        clearsStatus = StatusKey.NUMB,
        description = "Settle buzzing nerves. Deals 24 damage and clears Numb.",
    ),
    "mobility_aid" to MoveDefinition(
        id = "mobility_aid",
        label = "Mobility Aid",
        subLabel = "Clears Spin",
        type = MoveType.CURE,
        spoonCost = 1,
        power = 15,
        clearsStatus = StatusKey.VERTIGO,
        description = "Grounding aid. Deals 15 damage and clears Vertigo.",
    ),
    "push_through" to MoveDefinition(
        id = "push_through",
        label = "Push Through",
        subLabel = "Costs HP",
        type = MoveType.ATTACK,
        spoonCost = 0,
        description = "Fight through the pain. Costs 10% max HP. Hits harder at low health. " +
            "More than ${DEFAULT_BATTLE_CONFIG.pushThroughSafeUses} uses per battle permanently reduce max Spoons.",
    ),
)

internal val SYMPTOM_STRIKER_ENCOUNTERS: List<EncounterDefinition> = listOf(
    EncounterDefinition(
        index = 0,
        title = "Gym 1 · The Fatigue",
        accentColor = 0xFFFF9500,
        enemy = EnemyDefinition(
            id = "fatigue_entity",
            name = "Fatigue Entity",
            portraitRes = R.drawable.boss_fatigue_dragon,
            sprite = "(x_x)\nFATIGUE",
            maxHp = 100,
            normalPower = 12,
            specialPower = 10,
            specialChance = 0.30f,
            specialChanceEnraged = 0.55f,
            appliesStatus = StatusKey.LOCKED,
            specialDescription = "Nerve Spasm — muscles seize, attacks cost +1 Spoon",
        ),
        playerStartHp = 80,
        playerStartSpoons = 8,
        moves = listOf("rest", "box_breathing", "light_stretching", "physical_therapy", "push_through"),
        intro = "The Fatigue Entity lumbers forward. Heavy limbs, endless exhaustion.",
        symptomsDesc = "MS fatigue can be overwhelming. Nerve Spasm attacks lock your muscles — use Muscle Relax to clear Locked.",
        rewardMoveId = "adaptive_yoga",
    ),
    EncounterDefinition(
        index = 1,
        title = "Gym 2 · The Fog",
        accentColor = 0xFF88CCFF,
        enemy = EnemyDefinition(
            id = "fog_brain",
            name = "Fog Brain",
            portraitRes = R.drawable.boss_brain_fog_specter,
            sprite = "(~.~)\n~ FOG ~",
            maxHp = 115,
            normalPower = 13,
            specialPower = 11,
            specialChance = 0.35f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.FOGGED,
            specialDescription = "Brain Fog — one move gets blocked for 3 turns",
        ),
        playerStartHp = 90,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "light_stretching", "cognitive_therapy", "push_through"),
        intro = "The Fog Brain drifts into view. Confusion warps your thoughts.",
        symptomsDesc = "Cognitive fog dims your options each turn. Use Cog Therapy to clear Fogged.",
        rewardMoveId = "cognitive_therapy",
    ),
    EncounterDefinition(
        index = 2,
        title = "Gym 3 · The Heatwave",
        accentColor = 0xFFFF4500,
        enemy = EnemyDefinition(
            id = "heatwave_mirage",
            name = "Uhthoff's Phantom",
            portraitRes = R.drawable.boss_uhthoff_phantom,
            sprite = "(~_~)\n~ MIRAGE ~",
            maxHp = 120,
            normalPower = 15,
            specialPower = 10,
            specialChance = 0.30f,
            specialChanceEnraged = 0.55f,
            appliesStatus = StatusKey.OVERHEATED,
            specialDescription = "Heatwave — you begin overheating",
        ),
        playerStartHp = 110,
        playerStartSpoons = 8,
        moves = listOf("rest", "box_breathing", "light_stretching", "cooling_vest", "push_through"),
        intro = "The temperature rises one degree. Uhthoff's Phantom shimmers into reality.",
        symptomsDesc = "Heat can temporarily worsen symptoms. Cooling Vest clears Overheated before burn damage stacks up.",
        rewardMoveId = "cooling_vest",
    ),
    EncounterDefinition(
        index = 3,
        title = "Gym 4 · The Stiffness",
        accentColor = 0xFFB100FF,
        enemy = EnemyDefinition(
            id = "spasticity_golem",
            name = "Spasticity Golem",
            portraitRes = R.drawable.boss_spasticity_golem,
            sprite = "[=|_|=]\n~ GOLEM ~",
            maxHp = 135,
            normalPower = 18,
            specialPower = 11,
            specialChance = 0.32f,
            specialChanceEnraged = 0.58f,
            appliesStatus = StatusKey.LOCKED,
            specialDescription = "Concrete Spasm — attacks cost +1 Spoon",
        ),
        playerStartHp = 120,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "adaptive_yoga", "muscle_relaxant", "push_through"),
        intro = "A heavy clanking sound echoes. The Spasticity Golem blocks your path.",
        symptomsDesc = "Spasticity makes limbs feel rigid and painful. Muscle Relax clears Locked.",
        rewardMoveId = "muscle_relaxant",
    ),
    EncounterDefinition(
        index = 4,
        title = "Gym 5 · The Doubt",
        accentColor = 0xFF666666,
        enemy = EnemyDefinition(
            id = "doubt_shadow",
            name = "Doubt Shadow",
            portraitRes = R.drawable.boss_doubt_shadow,
            sprite = "\\(' _ ')/\n~ SHADOW ~",
            maxHp = 150,
            normalPower = 19,
            specialPower = 12,
            specialChance = 0.34f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.MASKED,
            specialDescription = "\"But You Look Fine\" — your gauges become masked",
        ),
        playerStartHp = 130,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "adaptive_yoga", "self_advocacy", "push_through"),
        intro = "A creeping sense of invalidation sets in. The Doubt Shadow appears.",
        symptomsDesc = "Invisible illness fuels self-doubt. Self-Advocacy clears Masked and reveals your gauges again.",
        rewardMoveId = "self_advocacy",
    ),
    EncounterDefinition(
        index = 5,
        title = "Gym 6 · The Blur",
        accentColor = 0xFF00FFFF,
        enemy = EnemyDefinition(
            id = "optic_phantom",
            name = "Optic Phantom",
            portraitRes = R.drawable.boss_optic_phantom,
            sprite = "((O_O))\n~ PHANTOM ~",
            maxHp = 165,
            normalPower = 21,
            specialPower = 13,
            specialChance = 0.34f,
            specialChanceEnraged = 0.60f,
            appliesStatus = StatusKey.BLURRED,
            specialDescription = "Optic Flare — your attacks lose clarity and power",
        ),
        playerStartHp = 150,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "self_advocacy", "corticosteroids", "push_through"),
        intro = "The edges of the world begin to fray. The Optic Phantom closes in.",
        symptomsDesc = "Blurred vision lowers your attack output. IV Steroids clears Blurred.",
        rewardMoveId = "corticosteroids",
    ),
    EncounterDefinition(
        index = 6,
        title = "Gym 7 · The Static",
        accentColor = 0xFFFF00FF,
        enemy = EnemyDefinition(
            id = "neuropathy_swarm",
            name = "Neuropathy Swarm",
            portraitRes = R.drawable.boss_neuropathy_swarm,
            sprite = ":::*:::\n~ SWARM ~",
            maxHp = 180,
            normalPower = 23,
            specialPower = 14,
            specialChance = 0.35f,
            specialChanceEnraged = 0.62f,
            appliesStatus = StatusKey.NUMB,
            specialDescription = "Pins & Needles — your hands go numb",
        ),
        playerStartHp = 180,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "adaptive_yoga", "nerve_meds", "push_through"),
        intro = "An electrical hum fills your ears. The Neuropathy Swarm descends.",
        symptomsDesc = "Peripheral neuropathy can feel like burning static. Nerve Meds clears Numb.",
        rewardMoveId = "nerve_meds",
    ),
    EncounterDefinition(
        index = 7,
        title = "Gym 8 · The Spin",
        accentColor = 0xFF00FFCC,
        enemy = EnemyDefinition(
            id = "vertigo_vortex",
            name = "Vertigo Vortex",
            portraitRes = R.drawable.boss_vertigo_vortex,
            sprite = "(@_@)\n~ VORTEX ~",
            maxHp = 200,
            normalPower = 25,
            specialPower = 15,
            specialChance = 0.36f,
            specialChanceEnraged = 0.64f,
            appliesStatus = StatusKey.VERTIGO,
            specialDescription = "Vertigo Spin — your attacks may miss for 3 turns",
        ),
        playerStartHp = 210,
        playerStartSpoons = 8,
        moves = listOf("rest", "listen_music", "adaptive_yoga", "mobility_aid", "push_through"),
        intro = "The Vertigo Vortex spins into view. The horizon vanishes. Balance is gone.",
        symptomsDesc = "Brainstem lesions can cause severe vertigo. Mobility Aid clears Vertigo and steadies your attacks.",
        rewardMoveId = "mobility_aid",
    ),
)
